site_name: Weave
site_description: Weave is a Clojure web framework that provides a simple and powerful way to build web applications.
site_url: https://github.com/nakkaya/weave

theme:
  favicon: https://raw.githubusercontent.com/nakkaya/weave/refs/heads/master/resources/public/weave.svg
  logo: https://raw.githubusercontent.com/nakkaya/weave/refs/heads/master/resources/public/weave.svg
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand
    - navigation.path

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  generator: false
