name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Clojure
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.11.1.1237.sh
          chmod +x linux-install-1.11.1.1237.sh
          sudo ./linux-install-1.11.1.1237.sh

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Download dependencies
        run: clojure -P

      - uses: nanasess/setup-chromedriver@v2

      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - run: clojure -X:test

  docs:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd doc
          pip install -r requirements.txt

      - name: Deploy documentation
        run: |
          cd doc
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
